// A static rotating list — same prompt for both partners on a given day,
// deterministic from the date so it doesn't need its own table.
export const DAILY_PROMPTS = [
  "Tell her one thing you've never told her before.",
  "Send a voice note right now — no reason needed.",
  "Name one thing about today that made you think of her.",
  "Write down a memory of the two of you, right now, before it fades.",
  "Tell him what you're most looking forward to about tonight.",
  "Send a photo of whatever's in front of you right now.",
  "Say out loud (or write) one thing you're grateful for about her today.",
  "Ask him a question you've never asked before.",
  "Tell her exactly what you love about the way she laughs.",
  "Plan one small thing to do together this week — say it out loud.",
  "Tell him about a moment today you wish he'd seen.",
  "Send a love note that's just one honest sentence.",
  "Describe your perfect ordinary Tuesday with her.",
  "Tell her the thing you're most proud of her for right now.",
  "Ask what's been on his mind lately that he hasn't said out loud.",
  "Recreate your first hello — say it to her again, right now.",
  "Tell him one way he's changed you for the better.",
  "Share a song that reminds you of her today.",
  "Write one sentence you'd want her to read on a hard day.",
  "Tell him about a dream you had, real or imagined for the future.",
  "Say thank you for something small he probably didn't notice.",
  "Tell her what home feels like when she's in it.",
  "Ask him what he needs more of from you this week.",
  "Send a voice note of you just saying her name and why you love it.",
  "Tell him the version of you that only he gets to see.",
  "Describe a place you'd love to take her, and why.",
  "Tell her one thing that made today feel lighter.",
  "Ask what he's been avoiding telling you — gently.",
  "Write down a compliment you've been meaning to say out loud.",
  "Tell her about a time she made you feel completely safe.",
  "Share one small fear, out loud, with him.",
  "Tell him what you'd want to be doing with her in ten years.",
  "Say the thing you're most grateful you never said to anyone but her.",
  "Ask her what love has felt like lately, honestly.",
  "Tell him about the smallest thing that made you smile today.",
  "Recreate a memory in one sentence, exactly as it happened.",
  "Tell her what you'd miss most if today were the last ordinary day.",
  "Ask him what he wishes you understood about him.",
  "Send a photo from years ago and say what it reminds you of.",
  "Tell her something you admire that you've never said aloud.",
  "Write the ending to: 'I knew I loved you when...'",
  "Tell him one thing you want to get better at, for the two of you.",
  "Ask her what her favorite version of you is.",
  "Tell him about a worry, and let him just listen.",
  "Say one thing you hope never changes between you.",
  "Tell her what today would have been like without her in it.",
  "Ask him for one thing he needs this week, no matter how small.",
  "Tell her the truth about how your day actually went.",
  "Write one line that belongs in your story, years from now.",
  "Say the words you almost said this morning but didn't.",
] as const;

export function getPromptForDate(date: Date): string {
  const epochDay = Math.floor(date.getTime() / 86_400_000);
  const index = ((epochDay % DAILY_PROMPTS.length) + DAILY_PROMPTS.length) % DAILY_PROMPTS.length;
  return DAILY_PROMPTS[index];
}
